Repository openshift/kuryr-kubernetes, pull requests merged in 2019-12, with the labels that each got.

#103 Update requirements, remove unused Dockerfiles
  openshift-kuryr-cni-ci-rhel8.Dockerfile
  openshift-kuryr-cni-ci.Dockerfile
  openshift-kuryr-cni-rhel8.Dockerfile
  openshift-kuryr-cni.Dockerfile
  openshift-kuryr-controller-ci-rhel8.Dockerfile
  openshift-kuryr-controller-ci.Dockerfile
  openshift-kuryr-controller-rhel8.Dockerfile
  openshift-kuryr-controller.Dockerfile
  openshift-kuryr-kubernetes-rhel8.spec
  openshift-kuryr-kubernetes.spec
  openshift-kuryr-tester-rhel8.Dockerfile
  openshift-kuryr-tester.Dockerfile
  tools/build-rpm-rhel8.sh
  tools/build-rpm.sh
Labels: approved, lgtm, size/L

#108 Bug 1754046: Ensure kuryr webhook is running before other operators' pods
  kuryr_kubernetes/cmd/webhook_server.py
  kuryr_kubernetes/config.py
  kuryr_kubernetes/tests/unit/cmd/test_status.py
  kuryr_kubernetes/tests/unit/test_k8s_client.py
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#111 bug 1784435: Lbaas deletion
  kuryr_kubernetes/controller/drivers/base.py
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_ingress_lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#113 Bug 1781198: Ensure namespace are recreated upon a k8s client failure
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_namespace.py
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#118 Rebase master
  .zuul.d/octavia.yaml
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/handlers/vif.py
Labels: approved, lgtm, size/M

#119 Bug 1779163: Nested CNI: Look for leftover ifaces to remove
  kuryr_kubernetes/cni/binding/base.py
  kuryr_kubernetes/cni/binding/bridge.py
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/tests/unit/cni/test_binding.py
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#121 Rebase master
  devstack/plugin.sh
  devstack/settings
  doc/source/installation/manual.rst
  lower-constraints.txt
  releasenotes/notes/k8s-client-token-default-882ec49d1faffc29.yaml
  requirements.txt
Labels: approved, lgtm, size/M

#122 Bug 1786299: Ensure LB sg update is retried when NP is enforced
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#124 Bug 1786140: Ensure LB member is removed upon pod removal
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#126 Bug 1785136: Ensure network leftovers without kuryrnet CRD obj are deleted
  kuryr_kubernetes/controller/handlers/namespace.py
Labels: approved, bugzilla/valid-bug, lgtm, size/M
