Repository openshift/kuryr-kubernetes, pull requests merged in 2019-11, with the labels that each got.

#79 Revert "Protect from keystoneauth 3.10.0 bug"
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, lgtm, size/XS

#80 Revert reversions of SR-IOV commits
  cni.Dockerfile
  cni_py3.Dockerfile
  controller.Dockerfile
  controller_py3.Dockerfile
  doc/source/installation/sriov.rst
  kuryr_kubernetes/clients.py
  kuryr_kubernetes/cmd/status.py
  kuryr_kubernetes/cni/binding/base.py
  kuryr_kubernetes/cni/binding/sriov.py
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/config.py
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/drivers/sriov.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/objects/vif.py
  kuryr_kubernetes/pod_resources/__init__.py
  kuryr_kubernetes/pod_resources/api.proto
  kuryr_kubernetes/pod_resources/api_pb2.py
  kuryr_kubernetes/pod_resources/api_pb2_grpc.py
  kuryr_kubernetes/pod_resources/client.py
  kuryr_kubernetes/tests/unit/cni/test_binding.py
  lower-constraints.txt
  requirements.txt
  tox.ini
Labels: approved, lgtm, size/XL

#81 Revert "Copy config options from kuryr-lib directly here"
  kuryr_kubernetes/clients.py
  kuryr_kubernetes/config.py
  kuryr_kubernetes/tests/unit/test_clients.py
Labels: approved, lgtm, size/M

#87 Bug 1777509: Fix deletion of ports on a pool
  kuryr_kubernetes/controller/drivers/vif_pool.py
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#88 Bug 1777492: Fix not handled exceptions causing Kuryr restarts
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/pipeline.py
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#89 Openshift rebase
  doc/source/installation/devstack/index.rst
  doc/source/installation/devstack/nested-dpdk.rst
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/config.py
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/tests/fake.py
  kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
Labels: approved, lgtm, size/L

#90 Bug 1777518: Handle not found subport on Trunk
  kuryr_kubernetes/controller/drivers/namespace_subnet.py
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#91 Update OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#92 Openshift rebase
  devstack/lib/kuryr_kubernetes
  doc/source/conf.py
  kuryr_kubernetes/cmd/status.py
  kuryr_kubernetes/cni/binding/base.py
  kuryr_kubernetes/cni/handlers.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/cni/utils.py
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy_security_groups.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_policy.py
  kuryr_kubernetes/tests/unit/controller/managers/test_pool.py
  kuryr_kubernetes/tests/unit/test_k8s_client.py
  releasenotes/source/conf.py
Labels: approved, lgtm, size/L

#99 Openshift rebase
  kuryr_kubernetes/controller/handlers/kuryrnet.py
Labels: approved, lgtm, size/XS

#98 Bug 1776894: Ensure pools population does not happen until pools are recovered
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
Labels: approved, bugzilla/valid-bug, lgtm, size/M
