Repository openshift/kuryr-kubernetes, pull requests merged in 2020-12, with the labels that each got.

#411 Bug 1896696: Ensure leftover loadbalancer is cleaned up
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/lbaas.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#413 Bug 1900491: Ensure members are deleted from pools when there is no endpoints
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#421 Bug 1890630: Ensure Ports in use per Subnet calculation is correct
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
  kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#422 Revert "Bug 1890630: Ensure Ports in use per Subnet calculation is correct"
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
  kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#423 Bug 1890630: Fix alert value for ports available on Subnet
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#426 Bug 1904973: Skip unscheduled pods when deleting NPs
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#429 Bug 1901495: Correctly compare SG rules in NP code
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
