Repository openshift/kuryr-kubernetes, pull requests merged in 2020-04, with the labels that each got.

#203 Fix grpcio build
  cni.Dockerfile
  controller.Dockerfile
Labels: approved, lgtm

#204 Fix sg rules creations for LB sg when applying members sg
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, lgtm

#206 Add component and subcomponent info to OWNERS
  OWNERS
Labels: approved, lgtm

#208 Bug 1818067:Ensure no attempt to deleted sg rules owned by Octavia happens
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#214 Bug 1826770: Update the Kuryr images to 4.5 repos
  openshift-kuryr-cni-ci-rhel8.Dockerfile
  openshift-kuryr-cni-rhel8.Dockerfile
  openshift-kuryr-controller-ci-rhel8.Dockerfile
  openshift-kuryr-controller-rhel8.Dockerfile
  openshift-kuryr-kubernetes-rhel8.spec
  openshift-kuryr-tester-rhel8.Dockerfile
  tools/build-rpm-rhel8.sh
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#215 Bug 1824258: Ensure LB state annotation sg matches the SG on the LB
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm
