Repository openshift/kuryr-kubernetes, pull requests merged in 2020-07, with the labels that each got.

#293 Increase kuryr controller prometheus bucket for pods creation
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
Labels: approved, lgtm

#295 Bug 1847011: Periodically fetch full list of watched resources
  kuryr_kubernetes/config.py
  kuryr_kubernetes/handlers/asynchronous.py
  kuryr_kubernetes/handlers/base.py
  kuryr_kubernetes/handlers/dispatch.py
  kuryr_kubernetes/handlers/k8s_base.py
  kuryr_kubernetes/handlers/logging.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/tests/unit/handlers/test_asynchronous.py
  kuryr_kubernetes/tests/unit/test_watcher.py
  kuryr_kubernetes/watcher.py
  lower-constraints.txt
  requirements.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#273 Bug 1845923: Get RPM and Kuryr version from git
  openshift-kuryr-kubernetes-rhel8.spec
  tools/build-rpm-rhel8.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#296 Sync RPM spec dependencies with requirements.txt
  openshift-kuryr-kubernetes-rhel8.spec
Labels: approved, lgtm

#298 Fix RPM spec pyroute2 version
  openshift-kuryr-kubernetes-rhel8.spec
Labels: approved, lgtm

#292 Bug 1786298: Bunch of kuryr-daemon NetlinkError fixes
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/cni/test_binding.py
  kuryr_kubernetes/tests/unit/cni/test_service.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#299 Bug 1829517: Attempt to autodetect interface in nested setups
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/tests/unit/cni/test_binding.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#291 Lbaas cleanup
  kuryr_kubernetes/controller/drivers/base.py
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_ingress_lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Labels: approved, lgtm

#302 Fix unit tests
  kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
Labels: approved, lgtm

#303 Bug 1856830: Fix duplicated sg rules on NP crd
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#309 Rebase from openstack/master
  .zuul.d/base.yaml
  .zuul.d/project.yaml
  .zuul.d/sdn.yaml
  playbooks/run_k8s_e2e_tests.yaml
  tools/gate/copy_k8s_logs.sh
Labels: approved, lgtm

#310 Bug 1860030: Civilize logging
  kuryr_kubernetes/cni/binding/bridge.py
  kuryr_kubernetes/cni/health.py
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/controller/handlers/policy.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/controller/managers/health.py
  kuryr_kubernetes/health.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/utils.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
