Repository openshift/kuryr-kubernetes, pull requests merged in 2020-11, with the labels that each got.

#389 Bug 1890472: Bulk port creation exception not completely formatted
  kuryr_kubernetes/clients.py
  kuryr_kubernetes/tests/unit/test_clients.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#391 Merge with opendev repository.
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
  kuryr_kubernetes/tests/unit/test_k8s_client.py
Labels: approved, lgtm

#393 Bug 1894194: Delete ports created for host networking pods
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/vif.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#392 Bug 1893996: Fix duplicated sg rules on NP crd
  kuryr_kubernetes/controller/drivers/network_policy.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#397 Rebase from openstack/master
  .zuul.d/base.yaml
  kuryr_cni/Gopkg.lock
  kuryr_cni/Gopkg.toml
  kuryr_cni/main.go
  kuryr_cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go
  kuryr_cni/vendor/github.com/containernetworking/cni/pkg/types/020/types.go
  kuryr_cni/vendor/github.com/containernetworking/cni/pkg/types/args.go
  kuryr_cni/vendor/github.com/containernetworking/cni/pkg/types/current/types.go
  kuryr_cni/vendor/github.com/containernetworking/cni/pkg/types/types.go
  kuryr_cni/vendor/github.com/containernetworking/cni/pkg/utils/utils.go
  kuryr_cni/vendor/github.com/pkg/errors/.travis.yml
  kuryr_cni/vendor/github.com/pkg/errors/Makefile
  kuryr_cni/vendor/github.com/pkg/errors/README.md
  kuryr_cni/vendor/github.com/pkg/errors/errors.go
  kuryr_cni/vendor/github.com/pkg/errors/go113.go
  kuryr_cni/vendor/github.com/pkg/errors/stack.go
  kuryr_kubernetes/cni/daemon/service.py
Labels: approved, lgtm

#398 Bug 1884584: Handle None or {} labels in match_selector()
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_utils.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#403 Fix calculation of Ports availability in Subnet
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
  kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
Labels: approved, lgtm

#405 Bug 1897142: Ensure members are deleted from pools when there is no endpoints
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#409 Tempest configs update and tox adjustements
  devstack/plugin.sh
  tox.ini
Labels: approved, lgtm

#406 Bug 1898906: Ensure members are deleted from pools when there is no endpoints
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#410 Bug 1899922: NP changes sometimes influence new pods/services.
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/tests/fake.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#415 Bug 1891559: Force pyroute2 0.5.7
  openshift-kuryr-kubernetes-rhel8.spec
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
