Repository openshift/kuryr-kubernetes, pull requests merged in 2020-06, with the labels that each got.

#250 Bug 1841493: Remove lb sg creation when octavia provider is ovn-octavia
  kuryr_kubernetes/config.py
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  releasenotes/notes/deprecate-sg-mode-option-96824c33335cd74b.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#252 Bump versions to 4.6
  openshift-kuryr-cni-ci-rhel8.Dockerfile
  openshift-kuryr-cni-rhel8.Dockerfile
  openshift-kuryr-controller-ci-rhel8.Dockerfile
  openshift-kuryr-controller-rhel8.Dockerfile
  openshift-kuryr-kubernetes-rhel8.spec
  openshift-kuryr-tester-rhel8.Dockerfile
  tools/build-rpm-rhel8.sh
Labels: approved, lgtm

#251 Bug 1841846: Ensure kuryrnetwork CRs without status can be deleted
  kuryr_kubernetes/controller/handlers/kuryrnetwork.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#257 Bug 1843674: Ensure security_groups on LBaaSLoadBalancer defaults to empty list
  kuryr_kubernetes/objects/lbaas.py
  kuryr_kubernetes/tests/unit/test_object.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#259 Bug 1842466: Ensure provider information is used when finding lbs
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#261 Bug 1843813: Ensure allowed_cidrs field is present on older openstacksdk versions
  kuryr_kubernetes/clients.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#263 [release-4.5] Bug 1843817: Ensure provider information is used when finding lbs
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, group-lead-approved, lgtm

#226 Export Prometheus metrics
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/prometheus_exporter.py
  kuryr_kubernetes/cni/utils.py
  kuryr_kubernetes/config.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
  kuryr_kubernetes/controller/service.py
  kuryr_kubernetes/tests/unit/cni/test_service.py
  kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
  openshift-kuryr-kubernetes-rhel8.spec
  requirements.txt
Labels: approved, lgtm

#267 Bug 1843342: Get RPM and Kuryr version from git
  openshift-kuryr-kubernetes-rhel8.spec
  tools/build-rpm-rhel8.sh
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#274 Bug 1846225: CNI: Don't wait for missing pods on DEL
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#271 Bug 1845914: Get RPM and Kuryr version from git
  openshift-kuryr-kubernetes-rhel8.spec
  tools/build-rpm-rhel8.sh
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, group-lead-approved, lgtm

#278 Bug 1846396: Remove ovn-octavia provider tcp+udp limitation
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#283 Bug 1846862: Add support for amphora to ovn-octavia upgrade
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#284 Bug 1847105: Fix hacking min version to 3.0.1
  kuryr_kubernetes/controller/drivers/sriov.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/utils.py
  test-requirements.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#280 Bug 1779163: CNI: Don't wait for missing pods on DEL
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#272 Bug 1845921: Get RPM and Kuryr version from git
  openshift-kuryr-kubernetes-rhel8.spec
  tools/build-rpm-rhel8.sh
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm
