Repository openshift/kuryr-kubernetes, pull requests merged in 2020-03, with the labels that each got.

#173 Rebase from openstack/kuryr-kubernetes
  .zuul.d/project.yaml
Labels: approved, lgtm, size/XS

#174 Bug 1810501: Ensures accurate quota calculation during the readiness checks
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/controller/handlers/policy.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/controller/managers/health.py
  kuryr_kubernetes/opts.py
  kuryr_kubernetes/tests/unit/controller/managers/test_health.py
  kuryr_kubernetes/utils.py
  releasenotes/notes/deprecate-handlers-caching-9cdfd772aba9a7ce.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#175 Bug 1810517: Ensure list of pods items is retrieved
  kuryr_kubernetes/controller/drivers/network_policy_security_groups.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy_security_groups.py
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#177 Rebase openshift/kuryr-kubernetes from https://opendev.org/openstack/kuryr-kubernetes
  .zuul.d/base.yaml
  contrib/pools-management/subports.py
  devstack/lib/kuryr_kubernetes
  kubernetes_crds/kuryrloadbalancer.yaml
  kubernetes_crds/kuryrnet.yaml
  kubernetes_crds/kuryrnetpolicy.yaml
  kubernetes_crds/network_attachment_definition_crd.yaml
  kuryr_kubernetes/cni/api.py
  kuryr_kubernetes/cni/binding/base.py
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/handlers.py
  kuryr_kubernetes/cni/health.py
  kuryr_kubernetes/cni/main.py
  kuryr_kubernetes/cni/plugins/base.py
  kuryr_kubernetes/controller/drivers/base.py
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/nested_vif.py
  kuryr_kubernetes/controller/drivers/public_ip.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/controller/managers/health.py
  kuryr_kubernetes/controller/managers/pool.py
  kuryr_kubernetes/controller/service.py
  kuryr_kubernetes/handlers/asynchronous.py
  kuryr_kubernetes/handlers/base.py
  kuryr_kubernetes/handlers/dispatch.py
  kuryr_kubernetes/objects/base.py
  kuryr_kubernetes/tests/unit/cmd/test_status.py
  kuryr_kubernetes/tests/unit/cni/test_api.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_base.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
  kuryr_kubernetes/tests/unit/handlers/test_asynchronous.py
  lower-constraints.txt
  requirements.txt
Labels: approved, lgtm, size/XL

#178 Bug 1810571: Raise K8sResourceNotFound for all client methods
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/test_k8s_client.py
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#179 Bug 1810574: Nested CNI: Remove interfaces on DEL requests
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/tests/unit/cni/test_binding.py
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#188 Gather OpenStack resources data
  kuryr_kubernetes/cmd/gather_openstack_data.py
  openshift-kuryr-kubernetes-rhel8.spec
  setup.cfg
Labels: approved, lgtm, size/M

#191 Gather quota information
  kuryr_kubernetes/cmd/gather_openstack_data.py
Labels: approved, lgtm

#192 Kuryr: Add apiVersion and kind to AC reponse
  kuryr_kubernetes/cmd/webhook_server.py
Labels: approved, lgtm

#194 [release-4.3] Bug 1815019: Ensures accurate quota calculation during the readiness checks
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/controller/handlers/policy.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/controller/managers/health.py
  kuryr_kubernetes/opts.py
  kuryr_kubernetes/tests/unit/controller/managers/test_health.py
  kuryr_kubernetes/utils.py
  releasenotes/notes/deprecate-handlers-caching-9cdfd772aba9a7ce.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm
