Repository openshift/kuryr-kubernetes, pull requests merged in 2020-10, with the labels that each got.

#358 Bug 1883166: Ensure only kuryr ports are cleaned up
  kuryr_kubernetes/controller/drivers/vif_pool.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#359 Bug 1884139: Set read timeout for any request in K8sClient
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/test_k8s_client.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#361 Bug 1882453: Ensure LB member is updated if a conflict happens
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#362 Updating kuryr-cni builder & base images to be consistent with ART
  openshift-kuryr-cni-rhel8.Dockerfile
Labels: approved, lgtm

#363 Updating kuryr-controller builder & base images to be consistent with ART
  openshift-kuryr-controller-rhel8.Dockerfile
Labels: approved, lgtm

#364 Updating kuryr-cni builder & base images to be consistent with ART
  openshift-kuryr-cni-rhel8.Dockerfile
Labels: approved, lgtm

#365 Updating kuryr-controller builder & base images to be consistent with ART
  openshift-kuryr-controller-rhel8.Dockerfile
Labels: approved, lgtm

#366 Bug 1884655: Add protection from unexpected issues
  kuryr_kubernetes/controller/drivers/vif_pool.py
Labels: approved, lgtm

#351 Bug 1860311: Civilize logging vol 2
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
  kuryr_kubernetes/utils.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#360 Bug 1884192: Set read timeout for any request in K8sClient
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/test_k8s_client.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#371 Rebase from master
  cni.Dockerfile
  controller.Dockerfile
Labels: approved, lgtm

#372 Bug 1886871: Fix is_host_network()
  kuryr_kubernetes/controller/drivers/utils.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#377 Make cni_ds_init find correct conflist files
  cni_ds_init
Labels: approved, lgtm

#378 Rebase from master
  doc/source/installation/devstack/containerized.rst
  doc/source/installation/ports-pool.rst
Labels: approved, lgtm

#383 Documentation update
  doc/source/installation/devstack/basic.rst
  doc/source/installation/network_policy.rst
Labels: approved, lgtm

#384 Bug 1886749: Removing network policy from namespace causes inability to access pods through loadbalancer.
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#386 Misc fixes
  contrib/vagrant/README.md
  devstack/lib/kuryr_kubernetes
  devstack/plugin.sh
  doc/source/installation/containerized.rst
  kuryr_kubernetes/controller/drivers/vif_pool.py
Labels: approved, lgtm
