Repository openshift/kuryr-kubernetes, pull requests merged in 2020-08, with the labels that each got.

#300 Bug 1855773: Attempt to autodetect interface in nested setups
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/tests/unit/cni/test_binding.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#317 Bug 1867534: Add finalizer for the pod as soon as possible.
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#318 Bug 1868427: Periodically fetch full list of watched resources
  kuryr_kubernetes/config.py
  kuryr_kubernetes/handlers/asynchronous.py
  kuryr_kubernetes/handlers/base.py
  kuryr_kubernetes/handlers/dispatch.py
  kuryr_kubernetes/handlers/k8s_base.py
  kuryr_kubernetes/handlers/logging.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/tests/unit/handlers/test_asynchronous.py
  kuryr_kubernetes/tests/unit/test_watcher.py
  kuryr_kubernetes/watcher.py
  lower-constraints.txt
  requirements.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#322 Bug 1869294: Ignore ResourceNotReady from update_lbaas_sg() when handling network policy
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#321 Bug 1867520: Support upgrading LBaaSState annotation to KLB CRD
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/objects/lbaas.py
  kuryr_kubernetes/utils.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#316 Adapt dockerfiles to work in both OKD and OCP
  openshift-kuryr-cni-ci-rhel8.Dockerfile
  openshift-kuryr-cni-rhel8.Dockerfile
  openshift-kuryr-controller-ci-rhel8.Dockerfile
  openshift-kuryr-controller-rhel8.Dockerfile
  tools/build-rpm-rhel8.sh
Labels: approved, lgtm

#324 Bug 1867538: Move vifs to 'status' in the KuryrPort CRD.
  kubernetes_crds/kuryr_crds/kuryrport.yaml
  kuryr_kubernetes/cni/binding/dpdk.py
  kuryr_kubernetes/cni/handlers.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/pod_label.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
  kuryr_kubernetes/utils.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#326 Bug 1871839: Ensure Service is delete if lb CRD is already gone
  kuryr_kubernetes/controller/handlers/lbaas.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#329 Bug 1873058: Convert KuryrLoadBalancer subsets CRD to EndpointSlice
  kubernetes_crds/kuryr_crds/kuryrloadbalancer.yaml
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#330 Bug 1869606: Remove the pod interface even if VIF is gone
  kuryr_kubernetes/cni/binding/base.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#331 Bug 1872265: Remove right finalizer on pod absence.
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
