Repository openshift/kuryr-kubernetes, pull requests merged in 2020-05, with the labels that each got.

#221 Bug 1828387: Ensure NP are enforced on SVC with different port and target port
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#235 Bug 1836187: Fix Kuryr CI for 3.11 branch
  openshift-kuryr-tester.Dockerfile
  tox.ini
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#231 Namespace SG driver: remove default egress rules
  kuryr_kubernetes/controller/drivers/namespace_security_groups.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_namespace_security_groups.py
Labels: approved, lgtm

#232 Remove remote_group_id usage at loadbalancer SGs
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/namespace_security_groups.py
Labels: approved, lgtm

#241 Bug 1838997: Fix hacking min version to 3.0.1
  test-requirements.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#240 Bug 1838985:Skip LB sg update when no endpoint is found
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#244 Bug 1810574: CNI: Confirm pods in cache before connecting
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/cni/test_service.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#245 Bug 1840187:Ensure LB resources with ERROR status are deleted
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#249 Bug 1839180: Remove lb sg creation when octavia provider is ovn-octavia
  kuryr_kubernetes/config.py
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  releasenotes/notes/deprecate-sg-mode-option-96824c33335cd74b.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
