Repository openshift/kuryr-kubernetes, pull requests merged in 2020-09, with the labels that each got.

#332 Bug 1872265: Guard against manually removing of KuryrPort CRD.
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#333 Bug 1873449: Ensure proper cleanup of subports
  kuryr_kubernetes/controller/drivers/namespace_subnet.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_namespace_subnet.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#335 Bug 1874439: Ignore CRD creation errors when ns is terminated
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/vif.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#336 Bug 1874504: Ensure LB sg is in sync with backend Pods
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#337 Bug 1874457: Skip FIP creation if no external subnet config is set
  kuryr_kubernetes/controller/drivers/lb_public_ip.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lb_public_ip.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#338 Bug 1875352: Ensure loadBalancerIP is used when defined on the Service
  kuryr_kubernetes/controller/handlers/lbaas.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#339 Bug 1873449: Delete ports without device_owner on ns deletion
  kuryr_kubernetes/controller/drivers/namespace_subnet.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#340 Bug 1875751: NP: Protect from disappearing resources
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/network_policy_security_groups.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#341 Bug 1867534: Catch exceptions for deleted pod.
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#342 Bug 1876571: Ensure updated lb sgs is used on the CRD
  kuryr_kubernetes/controller/handlers/loadbalancer.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#343 Bug 1875491:Clean lb crd status upon Load Balancer removal
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
  kuryr_kubernetes/utils.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#344 Bug 1876566: Leaks of loadbalancer
  kubernetes_crds/kuryr_crds/kuryrloadbalancer.yaml
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#345 Bug 1867534: Added new K8sFieldValueForbidden exception
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/k8s_client.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#346 Bug 1878725: Add iptables wrappers to Kuryr CNI
  images/iptables-scripts/ip6tables
  images/iptables-scripts/iptables
  openshift-kuryr-cni-rhel8.Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#348 Bug 1879855: Fix inability to determine Octavia version.
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#349 Bug 1860030: Civilize logging vol 2
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
  kuryr_kubernetes/utils.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#350 Bug 1881931: Skip KuryrLoadbalancer creation for Headless Service
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/handlers/lbaas.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#352 Bug 1883167: Avoid race when pod is deleted before finalizer is added
  kuryr_kubernetes/k8s_client.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#353 Bug 1883166: Cleanup ports belonging to deleted nodes
  kuryr_kubernetes/controller/drivers/vif_pool.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#355 Bug 1883825: Properly handle Kubernetes Exceptions
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#356 Bug 1883832: Ensure klb handler reacretes lb
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#357 Bug 1883565: Skip update of vip sg if lb is gone
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
