Repository openshift/kuryr-kubernetes, pull requests merged in 2021-11, with the labels that each got.

#439 Bug 2013496: Reap zombie child processes in CNI daemon service
  kuryr_kubernetes/cni/daemon/service.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#592 Bug 2019721: Update TOX_CONSTRAINTS_FILE for stable/xena
  cni.Dockerfile
  controller.Dockerfile
  tox.ini
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#594 Bug 2020664: Ensure DOWN subports are cleaned up
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#597 Bug 2019886: Improve retrieval of Trunks info
  kuryr_kubernetes/controller/drivers/neutron_vif.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/controller/handlers/pod_label.py
Labels: approved, lgtm

#603 RPM build: Get OpenStack repo version from arg
  tools/build-rpm-rhel8.sh
Labels: approved, lgtm

#600 Bug 2022722: Make completed Pods Ports reusable
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
  kuryr_kubernetes/tests/unit/test_utils.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#604 Bug 2023731: Ensure DOWN subports are cleaned up
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#585 Bug 2018129: Ensure KLB is updated
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
