Repository openshift/kuryr-kubernetes, pull requests merged in 2021-06, with the labels that each got.

#520 Bug 1968436: Fix Listener timeouts update
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#521 Bug 1969397: Workaround OVN bug causing subports to be DOWN
  kuryr_kubernetes/cni/handlers.py
  kuryr_kubernetes/controller/drivers/base.py
  kuryr_kubernetes/controller/drivers/nested_dpdk_vif.py
  kuryr_kubernetes/controller/drivers/nested_macvlan_vif.py
  kuryr_kubernetes/controller/drivers/nested_vlan_vif.py
  kuryr_kubernetes/controller/drivers/neutron_vif.py
  kuryr_kubernetes/controller/drivers/sriov.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/controller/handlers/machine.py
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/controller/handlers/pod_label.py
  kuryr_kubernetes/controller/handlers/policy.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/handlers/k8s_base.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
  kuryr_kubernetes/tests/unit/handlers/test_retry.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#526 Rebase from upstream master
  .zuul.d/base.yaml
  .zuul.d/multi-vif.yaml
  .zuul.d/multinode.yaml
  .zuul.d/octavia.yaml
  .zuul.d/project.yaml
  .zuul.d/sdn.yaml
  cni.Dockerfile
  devstack/files/debs/kuryr-kubernetes
  devstack/files/rpms/kuryr-kubernetes
  devstack/lib/kubernetes
  devstack/lib/kuryr_kubernetes
  devstack/local.conf.odl.sample
  devstack/local.conf.openshift.sample
  devstack/local.conf.ovn.sample
  devstack/local.conf.pod-in-vm.overcloud.sample
  devstack/local.conf.pod-in-vm.undercloud.odl.sample
  devstack/local.conf.sample
  devstack/local.conf.worker.sample
  devstack/plugin.sh
  devstack/settings
  doc/source/contributor/contributing.rst
  doc/source/installation/devstack/basic.rst
  doc/source/installation/network_policy.rst
  kuryr_cni/Gopkg.lock
  kuryr_cni/Gopkg.toml
  kuryr_cni/go.mod
  kuryr_cni/go.sum
  kuryr_cni/hack/build-go.sh
  kuryr_cni/hack/update-deps.sh
  kuryr_cni/pkg/main.go
  kuryr_cni/pkg/ovo.go
  kuryr_cni/vendor/github.com/pkg/errors/.gitignore
  kuryr_cni/vendor/github.com/pkg/errors/.travis.yml
  kuryr_cni/vendor/github.com/pkg/errors/LICENSE
  kuryr_cni/vendor/github.com/pkg/errors/Makefile
  kuryr_cni/vendor/github.com/pkg/errors/README.md
  kuryr_cni/vendor/github.com/pkg/errors/appveyor.yml
  kuryr_cni/vendor/github.com/pkg/errors/errors.go
  kuryr_cni/vendor/github.com/pkg/errors/go113.go
  kuryr_cni/vendor/github.com/pkg/errors/stack.go
  kuryr_cni/vendor/modules.txt
  kuryr_kubernetes/cni/binding/base.py
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/cni/binding/sriov.py
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/utils.py
  kuryr_kubernetes/config.py
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
  kuryr_kubernetes/tests/unit/test_watcher.py
  openshift-kuryr-cni-rhel8.Dockerfile
  playbooks/run_k8s_e2e_tests.yaml
  releasenotes/notes/changing-default-url-for-k8s-api-42c3b90183783291.yaml
  setup.cfg
  tools/gate/copy_k8s_logs.sh
  tox.ini
Labels: approved, lgtm

#519 [release-4.6] Bug 1968418: Fixing bug, Kuryr-Controller crashes when it's missing the status
  kuryr_kubernetes/controller/handlers/loadbalancer.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#531 Add listeners, pools and members to must-gather
  kuryr_kubernetes/cmd/gather_openstack_data.py
Labels: approved, lgtm

#525 Bug 1972631: Workaround OVN bug causing subports to be DOWN
  kuryr_kubernetes/cni/handlers.py
  kuryr_kubernetes/controller/drivers/base.py
  kuryr_kubernetes/controller/drivers/nested_dpdk_vif.py
  kuryr_kubernetes/controller/drivers/nested_macvlan_vif.py
  kuryr_kubernetes/controller/drivers/nested_vlan_vif.py
  kuryr_kubernetes/controller/drivers/neutron_vif.py
  kuryr_kubernetes/controller/drivers/sriov.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/controller/handlers/machine.py
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/controller/handlers/pod_label.py
  kuryr_kubernetes/controller/handlers/policy.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/handlers/k8s_base.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
  kuryr_kubernetes/tests/unit/handlers/test_retry.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
