Repository openshift/kuryr-kubernetes, pull requests merged in 2021-09, with the labels that each got.

#552 Switch dockerfiles to use Rocky's RDO
  openshift-kuryr-cni-ci.Dockerfile
  openshift-kuryr-controller-ci.Dockerfile
Labels: approved, lgtm

#558 Bug 2002548: Fix health checks on large scale environments
  kuryr_kubernetes/clients.py
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/controller/handlers/policy.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/controller/managers/health.py
  kuryr_kubernetes/tests/unit/controller/managers/test_health.py
  kuryr_kubernetes/tests/unit/kuryr_fixtures.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#566 Bug 2005355: tox tests: Pin virtualenv to 20.7.2
  openshift-kuryr-tester-rhel8.Dockerfile
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#557 Bug 2002171: remove port from trunk on _cleanup_leftover_ports
  kuryr_kubernetes/controller/drivers/namespace_subnet.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#548 Bug 1991537: Clean LB status when LB is removed from Octavia
  .dockerignore
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/public_ip.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#572 Bug 2002548: Ensure quotas values are fetched as attributes
  kuryr_kubernetes/controller/handlers/namespace.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
