Repository openshift/kuryr-kubernetes, pull requests merged in 2021-12, with the labels that each got.

#610 Bug 2028816: Fix VLAN ID management
  kuryr_kubernetes/controller/drivers/nested_vlan_vif.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#608 Bug 2028396: Make completed Pods Ports reusable
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
  kuryr_kubernetes/tests/unit/test_utils.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#602 Bug 2023383: Do not start kuryr-daemon when worker_num <= 1
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/exceptions.py
  lower-constraints.txt
  requirements.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#614 Pod and Services events
  kuryr_kubernetes/clients.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/controller/handlers/pipeline.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/handlers/logging.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_pipeline.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm

#615 Lock pool population, events follow up
  doc/source/installation/ports-pool.rst
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm

#607 Bug 2028307: [4.8] Do not restart Kuryr-Controller when LB is stuck in PENDING_UPDATE state or Neutron port is DOWN
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/nested_vlan_vif.py
  kuryr_kubernetes/controller/drivers/neutron_vif.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/handlers/retry.py
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#618 Bug 2034898: Added missing raise statement for not ready resource.
  kuryr_kubernetes/controller/handlers/kuryrport.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#619 Bug 2035333: Limit the number of concurrent create_ports requests
  kuryr_kubernetes/controller/drivers/base.py
  kuryr_kubernetes/controller/drivers/nested_vlan_vif.py
  kuryr_kubernetes/controller/drivers/neutron_vif.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_nested_vlan_vif.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_neutron_vif.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
