Repository openshift/kuryr-kubernetes, pull requests merged in 2021-07, with the labels that each got.

#533 Bug 1975676: Workaround OVN bug causing subports to be DOWN
  kuryr_kubernetes/cni/handlers.py
  kuryr_kubernetes/controller/drivers/base.py
  kuryr_kubernetes/controller/drivers/nested_dpdk_vif.py
  kuryr_kubernetes/controller/drivers/nested_macvlan_vif.py
  kuryr_kubernetes/controller/drivers/nested_vlan_vif.py
  kuryr_kubernetes/controller/drivers/neutron_vif.py
  kuryr_kubernetes/controller/drivers/sriov.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/controller/handlers/pod_label.py
  kuryr_kubernetes/controller/handlers/policy.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/handlers/k8s_base.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
  kuryr_kubernetes/tests/unit/handlers/test_retry.py
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#538 Expose critical lbs metrics
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
  kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm

#536 Added metrics for failures caused by OpenStack services.
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
  kuryr_kubernetes/handlers/retry.py
Labels: approved, lgtm

#539 gracefully exit daemonserver before registry exit
  kuryr_kubernetes/cni/daemon/service.py
Labels: approved, lgtm

#540 Bug 1983107: Allow clean up of unused member
  kuryr_kubernetes/controller/handlers/loadbalancer.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#541 Bug 1983107: Fix KLB conversion from annotations
  kuryr_kubernetes/controller/handlers/lbaas.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
