Repository openshift/kuryr-kubernetes, pull requests merged in 2021-04, with the labels that each got.

#494 Update OWNERS
  OWNERS
Labels: approved, lgtm

#491 Handle default Kubernetes Service
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm

#496 Bug 1947343: NPs: Do not set ports for protocol-less SG rules
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#498 Bug 1921878: Include service subnet to be open for namespaceSelector set to all.
  kuryr_kubernetes/controller/drivers/network_policy.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#499 Bug 1933880: Fixing bug, Kuryr-Controller crashes when it's missing the status
  kuryr_kubernetes/controller/handlers/loadbalancer.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#503 Bug 1949480: Fix constant update of Listeners timeout
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#506 Bug 1932114: Allow to config network MTU
  kuryr_kubernetes/cni/binding/bridge.py
  kuryr_kubernetes/config.py
  kuryr_kubernetes/controller/drivers/namespace_subnet.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
