Repository openshift/kuryr-kubernetes, pull requests merged in 2021-03, with the labels that each got.

#463 Bug 1918568: Fix LB handling with ACLs and ERROR state
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#467 Bug 1918568: Raise ResourceNotReady when deleting ERROR LB
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#470 Bug 1924075: Skip pool pre population if no Status is present on CRD
  kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetwork_population.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#476 Bug 1937459: Fix Subnet retrival when creating Service without Selector
  kuryr_kubernetes/controller/handlers/loadbalancer.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#481 Bug 1918568: Fix TypeError on ERROR LB removal
  kuryr_kubernetes/controller/drivers/lbaasv2.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#427 Bug 1897526: Fix ports count on subnet
  kuryr_kubernetes/controller/managers/prometheus_exporter.py
  kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#485 Bug 1939961: Ensure LB member is updated if a conflict happens
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#482 Bug 1937991: CNI: Lookup offending interface on NetlinkError
  kuryr_kubernetes/cni/binding/nested.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#487 Bug 1938960: Ignore headless services in NP code
  kuryr_kubernetes/controller/drivers/network_policy.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#484 Bug 1940141: Do not default protocol to TCP for allow-all NPs
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/utils.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#492 Bug 1936342: kuryr-controller restarting after 3 days cluster running - pools without members
  kuryr_kubernetes/controller/handlers/loadbalancer.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
