Repository openshift/kuryr-kubernetes, pull requests merged in 2021-01, with the labels that each got.

#431 Bug 1904973: Skip unscheduled pods when handling NP creation
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#436 Bug 1915672: Handle absence of selfLink on Kuryr-Kubernetes
  doc/source/installation/network_policy.rst
  doc/source/specs/queens/network_policy.rst
  kuryr_kubernetes/cmd/status.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/sriov.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/controller/handlers/namespace.py
  kuryr_kubernetes/controller/handlers/pod_label.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/handlers/retry.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/os_vif_util.py
  kuryr_kubernetes/tests/fake.py
  kuryr_kubernetes/tests/unit/cmd/test_status.py
  kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_multi_vif.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_namespace_subnet.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy_security_groups.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_sriov.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetwork.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetworkpolicy.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_namespace.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_pod_label.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_policy.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
  kuryr_kubernetes/tests/unit/handlers/test_retry.py
  kuryr_kubernetes/tests/unit/test_k8s_client.py
  kuryr_kubernetes/tests/unit/test_os_vif_util.py
  kuryr_kubernetes/tests/unit/test_utils.py
  kuryr_kubernetes/utils.py
  kuryr_kubernetes/watcher.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#420 Bug 1889946: Bunch of CNI fixes related to cri-o
  kuryr_kubernetes/cni/binding/base.py
  kuryr_kubernetes/cni/binding/bridge.py
  kuryr_kubernetes/cni/binding/nested.py
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/cni/test_binding.py
  kuryr_kubernetes/tests/unit/cni/test_service.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#437 Bug 1920481: Decrease CPU usage of Prometheus exporter
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/tests/unit/cni/test_service.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#438 Bug 1915885: Support multiple nodes subnets
  doc/source/installation/containerized.rst
  doc/source/installation/devstack/nested-macvlan.rst
  doc/source/installation/devstack/nested-vlan.rst
  doc/source/nested_vlan_mode.rst
  kuryr_kubernetes/config.py
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/drivers/base.py
  kuryr_kubernetes/controller/drivers/nested_vif.py
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/node_subnets.py
  kuryr_kubernetes/controller/handlers/loadbalancer.py
  kuryr_kubernetes/controller/handlers/machine.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_nested_vif.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_node_subnets.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_machine.py
  kuryr_kubernetes/tests/unit/test_utils.py
  kuryr_kubernetes/utils.py
  releasenotes/notes/deprecate-worker-nodes-subnet-e452c84df5b5ed5c.yaml
  setup.cfg
  tools/generate_k8s_resource_definitions.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
