Repository openshift/kuryr-kubernetes, pull requests merged in 2021-05, with the labels that each got.

#507 Bug 1952429: Narrow connection to the cluster only on namespaceSelector.
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
  kuryr_kubernetes/utils.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#504 Bug 1941941: Include service subnet to be open for namespaceSelector set to all.
  kuryr_kubernetes/controller/drivers/network_policy.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#510 Bug 1920532: Fix NPs for OVN LBs with hairpin traffic
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/network_policy_security_groups.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy_security_groups.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_utils.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetwork.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#514 Bug 1957315: Fix readiness quota check
  kuryr_kubernetes/utils.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#517 Bug 1933880: Ignore 422 Unprocessable Entity on KLB patching
  kuryr_kubernetes/controller/handlers/loadbalancer.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#515 Bug 1954353: Ensure LB resources with ERROR status are deleted
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#508 Bug 1955024: CNI: Use golang 1.15 for building
  openshift-kuryr-cni-ci.Dockerfile
  openshift-kuryr-cni.Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#518 Bug 1963846: Fix NPs for OVN LBs with hairpin traffic
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/network_policy_security_groups.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork.py
  kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
  kuryr_kubernetes/controller/handlers/kuryrport.py
  kuryr_kubernetes/controller/handlers/lbaas.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy_security_groups.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_utils.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetwork.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
