Repository openshift/kuryr-kubernetes, pull requests merged in 2022-04, with the labels that each got.

#647 Bug 2070047: Increase cni_request_duration buckets
  kuryr_kubernetes/cni/prometheus_exporter.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#655 Parallelize ports removal.
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/drivers/namespace_subnet.py
  kuryr_kubernetes/controller/drivers/nested_vlan_vif.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/drivers/vif_pool.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_nested_vlan_vif.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
Labels: approved, lgtm

#645 Bug 1983056: CNI: Use K8S_POD_UID passed from CRI
  kubernetes_crds/kuryr_crds/kuryrport.yaml
  kuryr_kubernetes/cni/binding/base.py
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/cni/utils.py
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/controller/handlers/vif.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py
  kuryr_kubernetes/utils.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#657 Bug 1997120: CNI: Watch for deleted pods
  kuryr_kubernetes/cni/daemon/service.py
  kuryr_kubernetes/cni/daemon/watcher_service.py
  kuryr_kubernetes/cni/handlers.py
  kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
  kuryr_kubernetes/constants.py
  kuryr_kubernetes/exceptions.py
  kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py
  kuryr_kubernetes/tests/unit/cni/test_handlers.py
  kuryr_kubernetes/tests/unit/cni/test_service.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#658 Merge from upstream
  .zuul.d/base.yaml
  .zuul.d/k8s-np-e2e.yaml
  .zuul.d/tempest-jobs.yaml
  .zuul.d/tempest-multinode-jobs.yaml
  kuryr_kubernetes/controller/drivers/lbaasv2.py
  kuryr_kubernetes/controller/drivers/namespace_subnet.py
  kuryr_kubernetes/controller/drivers/network_policy.py
  kuryr_kubernetes/controller/drivers/utils.py
  kuryr_kubernetes/controller/handlers/kuryrnetwork.py
  kuryr_kubernetes/k8s_client.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_namespace_subnet.py
  kuryr_kubernetes/tests/unit/controller/drivers/test_utils.py
  kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetwork.py
Labels: approved, lgtm
